name: Build firmware
run-name: build-firmware / (${{ github.ref }})
on: push
jobs:
  build-firmware:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/matzes/heinerbloch-devenv:latest
    steps:
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: true

      - run: rake build:rp2350

      - name: Archive firmware binaries
        uses: actions/upload-artifact@v4
        with:
          name: rp2350-firmware
          path: |
            platform/rp2350/build/heinerbloch-rp2350.bin
            platform/rp2350/build/heinerbloch-rp2350.elf
            platform/rp2350/build/heinerbloch-rp2350.uf2
